# Generated by Django 3.2.4 on 2024-04-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['restaurant_id'], name='app_menu_restaur_809432_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_time'], name='app_order_deliver_67824e_idx'),
        ),
    ]
