# Generated by Django 3.2.4 on 2024-04-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240423_1831'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='app_order_deliver_67824e_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['time_placed'], name='app_order_time_pl_d91c60_idx'),
        ),
    ]
